"""Create initial tables

Revision ID: 001
Revises: 
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_complet', sa.String(), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('ville_naissance', sa.String(), nullable=False),
    sa.Column('pays_naissance', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('etablissement', sa.String(), nullable=False),
    sa.Column('niveau_etude', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    
    op.create_table('logements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('code_postal', sa.String(), nullable=False),
    sa.Column('loyer', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('DISPONIBLE', 'OCCUPE', 'MAINTENANCE', name='statutlogement'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logements_id'), 'logements', ['id'], unique=False)
    
    op.create_table('souscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('logement_id', sa.Integer(), nullable=False),
    sa.Column('date_entree', sa.Date(), nullable=False),
    sa.Column('duree_location', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('ATTENTE_PAIEMENT', 'PAYE', 'LIVRE', 'CLOTURE', name='statutsouscription'), nullable=True),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['logement_id'], ['logements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_souscriptions_id'), 'souscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_souscriptions_reference'), 'souscriptions', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_souscriptions_reference'), table_name='souscriptions')
    op.drop_index(op.f('ix_souscriptions_id'), table_name='souscriptions')
    op.drop_table('souscriptions')
    op.drop_index(op.f('ix_logements_id'), table_name='logements')
    op.drop_table('logements')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###